// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzcZeZPwhyTKOFbqSkwu-IyFVwd1Ip8dg',
    appId: '1:406139201995:web:b8bf2751968b669e3dee4e',
    messagingSenderId: '406139201995',
    projectId: 'washli-2a77a',
    authDomain: 'washli-2a77a.firebaseapp.com',
    storageBucket: 'washli-2a77a.firebasestorage.app',
    measurementId: 'G-HD4SWP0LKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYkM2u06giSMhT02ZCCGem2QxCVuS29Hw',
    appId: '1:406139201995:android:9de0877763d8240d3dee4e',
    messagingSenderId: '406139201995',
    projectId: 'washli-2a77a',
    storageBucket: 'washli-2a77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfEHlrUf2nevRvobSehX9TGxISO_xltI',
    appId: '1:406139201995:ios:9f9693b5b086dda73dee4e',
    messagingSenderId: '406139201995',
    projectId: 'washli-2a77a',
    storageBucket: 'washli-2a77a.firebasestorage.app',
    iosBundleId: 'com.washli.washlimobile.washliMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXfEHlrUf2nevRvobSehX9TGxISO_xltI',
    appId: '1:406139201995:ios:9f9693b5b086dda73dee4e',
    messagingSenderId: '406139201995',
    projectId: 'washli-2a77a',
    storageBucket: 'washli-2a77a.firebasestorage.app',
    iosBundleId: 'com.washli.washlimobile.washliMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzcZeZPwhyTKOFbqSkwu-IyFVwd1Ip8dg',
    appId: '1:406139201995:web:fb83a202876da5cb3dee4e',
    messagingSenderId: '406139201995',
    projectId: 'washli-2a77a',
    authDomain: 'washli-2a77a.firebaseapp.com',
    storageBucket: 'washli-2a77a.firebasestorage.app',
    measurementId: 'G-68CZDSP9JR',
  );
}
